Improve output messages
git-svn-id: https://clas12svn.jlab.org/repos/clas12/Clara/stress_test@10847 b9d438ff-8729-0410-a4ab-d2f36c9c72ed

diff --git a/stress/start b/stress/start
--- a/stress/start
+++ b/stress/start
@@ -86,15 +86,19 @@ case $PLATFORM_HOST in
         ;;
 esac
 
-if [[ $NUMBER_OF_NODES -gt 0 && -z $NODES_FILE ]]; then
-    echo "A file with the list of available nodes is required."
-    echo "See nodes/quark.list as an example."
-    echo
-    usage
-    exit 1
+if [[ $NUMBER_OF_NODES -gt 0 ]]; then
+    if [[ -z $NODES_FILE ]]; then
+        echo "A file with the list of available nodes is required."
+        echo "See nodes/quark.list as an example."
+        echo
+        usage
+        exit 1
+    fi
+    echo "NODES_FILE=$NODES_FILE"
+else
+    echo "Running everything on platform node. No extra DPEs will be deployed."
 fi
 
-echo "NODES_FILE=$NODES_FILE"
 
 ##############################################################################
 # Start the platform and the DPEs
